apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: two-tier
  name: mysql-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"

