apiVersion: v1
kind: Service
metadata:
  labels:
    app: two-tier-app
  name: two-tier-app-service
  namespace: two-tier
spec:
  selector:
    app: two-tier-app
  type: NodePort
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 5000 
      nodePort: 30007
